export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_PROFILES = 'GET_PROFILES'
export const PROFILE_ERROR = 'PROFILE_ERROR'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'
export const EDIT_PROFILE = 'EDIT_PROFILE'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const GET_REPOS = 'GET_REPOS'
export const CLEAR_REPOS = 'CLEAR_REPOS'
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
export const CLEAR_POST = 'CLEAR_POST'
export const POST_ERROR = 'POST_ERROR'
export const GET_PROYECTOS ='GET_PROYECTOS'
export const GET_PROYECTO ='GET_PROYECTO'
export const PROYECTO_ERROR = 'PROYECTO_ERROR'
export const CLEAR_PROYECTOS ='CLEAR_PROYECTOS'
export const UPDATE_LIKES = 'UPDATE_LIKES'
export const DELETE_POST = 'DELETE_POST'
export const ADD_POST = 'ADD_POST' 
export const ADD_COMMENT = 'ADD_COMMENT'
export const REMOVE_COMMENT = 'REMOVE_COMMENT'
export const GET_ANUNCIOS = 'GET_ANUNCIOS'
export const GET_ANUNCIO = 'GET_ANUNCIO'
export const ADD_ANUNCIO = 'ADD_ANUNCIO' 
export const DELETE_ANUNCIO = 'DELETE_ANUNCIO'
export const CLEAR_ANUNCIOS = 'CLEAR_ANUNCIOS'
export const ANUNCIOS_ERROR = 'ANUNCIOS_ERROR'





//Asignamos constantes las cuales van a especificar el tipo de accion a realizar 
 
